### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by xmarshalldteachx** [vdrmota/Social-Media-and-Contact-Info-Extractor#26]
Hey guys. Im noob. How can I install it? Thank you

**Comment by pocesar** [comment]
you can download the zip https://github.com/vdrmota/Social-Media-and-Contact-Info-Extractor/archive/master.zip, unpack, then install using npm and run using apify cli https://docs.apify.com/cli

**Comment by jancurn** [comment]
And of course, you can run it without installation on Apify: https://apify.com/vdrmota/contact-info-scraper
