### ISSUE TITLE
Can this be run locally

### ISSUE THREAD

**Issue by MSIH** [vdrmota/Social-Media-and-Contact-Info-Extractor#36]
When i try to run this locally I am getting error:

(node:1723466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:1723466) UnhandledPromiseRejectionWarning: ApifyApiError: By launching this job you would exceed the memory limit of 4096MB for all your actors (currently used: 4096MB, requested: 4096MB). Please upgrade to a paid plan to increase your actor memory limit.
  clientMethod: undefined
  statusCode: 402
  type: actor-memory-limit-exceeded
  attempt: 1
  httpMethod: post
  path: /v2/acts/vdrmota~contact-info-scraper/runs
  stack: 
    at makeRequest (/home/msihadmin/Documents/apify-pricelocal/node_modules/apify-client/src/http_client.js:136:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1723466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)

**Comment by pocesar** [comment]
you'd need to clone the repo and execute it in your machine, not on the platform. check the guide here on how to do it https://sdk.apify.com/docs/guides/quick-start
