### ISSUE TITLE
When running locally on linux chrome page showing

### ISSUE THREAD

**Issue by MSIH** [vdrmota/Social-Media-and-Contact-Info-Extractor#41]
I am running this locally on my computer running Linux.

When I run the script many chrome pages open up on my screen.

How can I run this headless?

**Comment by pocesar** [comment]
how are you running this? you can set the environment variable `APIFY_HEADLESS=1` before running it

**Comment by MSIH** [comment]
No but I fixed the problem by adding launchOptions:

```
launchContext: {
            useIncognitoPages: true,
            useChrome: false,
            launchOptions: {
                headless: true,
            }
        },
```
